### ISSUE TITLE
Build on Mac OSX fails

### ISSUE THREAD

**Issue by echox** [Softmotions/ejdb-java#1]
After running configure a wrong include path is used, e.g.:

    -I/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home//include/linux

therefore the build fails with:

    In file included from ./src/cpp/org_ejdb_driver_EJDB.h:2:
    /Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home//include/jni.h:45:10: fatal error:
    'jni_md.h' file not found
    #include "jni_md.h"
             ^
    1 error generated.

On OSX it should be:

    -I/Library/Java/JavaVirtualMachines/jdk1.7.0_71.jdk/Contents/Home//include/darwin

**Comment by obourdon** [comment]
Hello again

my clone of the ejdb-java git repo should fix this issue
Best regards

**Comment by echox** [comment]
as mentioned in the other comment, works perfectly, thanks.
Should be merged back :+1:

**Comment by obourdon** [comment]
Many thanks again for the feedback, as I mentioned in the other issue the pull request has been done few minutes ago. Best regards
